#!/bin/bash

# Start VNC server on display :1
vncserver -localhost no -geometry 800x800 :1

# List the VNC servers to verify the correct one is running
vncserver -list

# Open the VNC viewer
termux-open vnc://127.0.0.1:5901
